[package]
name = "cpu_rasteriser"
version = "0.5.0"
edition = "2024"

[dependencies]
minifb = "0.28"
softbuffer = "0.4.8"
winit = "0.30.13"
threadpool = "1.8.1"
rasteriser_macros = { path = "../rasteriser_macros" }
wide = "1.6.1"

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "rasterise_segment"
harness = false

